name: vicodin
description: Vicodin is a very simple and yet very useful pure Dart dependency container.
version: 1.0.5
homepage: https://github.com/glynskyi/vicodin

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.8
