name: vicodin
description: Vicodin is a very simple and yet very useful pure Dart dependency container.
version: 1.0.5-nullsafety.0
homepage: https://github.com/glynskyi/vicodin

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.16.0-nullsafety.18
  pedantic: ^1.10.0-nullsafety.3